let tokens = "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc0OTg3NDIwLCJpYXQiOjE2NzQ5ODY1MjAsImp0aSI6ImJmZTMxZmRjMTQyNjQyYmNhODExNWQxYTNmYWExOGJmIiwidXNlcl9pZCI6MX0.xcQZT3sAsaWx-luzKtk2NFEMf4b797lxkpBsySKkBDo";

export default tokens;