let tokens = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNjc2Mjg0ODI4LCJpYXQiOjE2NzYyODM5MjgsImp0aSI6ImE5OWEwNDNlMWViYzQ1YTViZTk4MTZlYmJkMGI3MGIxIiwidXNlcl9pZCI6MX0.jorVUAiyeqRQ3n1cxBDAxgSz4csLDOahFjyCOzq6uIg"


export default tokens;